//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORNG_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasActivationDocuments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GasActivationDocuments()
        {
            this.Notifications = new HashSet<Notifications>();
            this.Payments = new HashSet<Payments>();
        }
    
        public int DocumentId { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> SpecialistId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Address { get; set; }
        public string MeterNumber { get; set; }
        public decimal InitialMeterReading { get; set; }
        public System.DateTime ActivationDate { get; set; }
        public byte[] DocumentScan { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notifications> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
