//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORNG_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NotificationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual GasActivationDocuments GasActivationDocuments { get; set; }
        public virtual Users Users { get; set; }
    }
}
